FROM docker.io/library/python:3.12-slim

ARG CONTAINER_UID=1000
ARG CONTAINER_GID=1000

# INSTALL SYSTEM DEPENDENCIES #################################################

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash-completion \
    build-essential \
    curl \
    git \
    graphviz \
    just \
    less \
    libbox2d2 \
    locales \
    make \
    neovim \
    swig \
    vim \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user.
RUN groupadd --gid ${CONTAINER_GID} user \
  && useradd --uid ${CONTAINER_UID} --gid ${CONTAINER_GID} --no-log-init --shell /bin/bash --create-home user

# Switch to the non-root user.
USER user

# Make the Python user-installed commands available in all processes.
ENV PATH="/home/user/.local/bin:${PATH}"